// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/broker.proto

package brokerpbconnect

import (
	brokerpb "broker/proto/brokerpb"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BrokerServiceName is the fully-qualified name of the BrokerService service.
	BrokerServiceName = "broker.v1.BrokerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BrokerServiceLaunchProcedure is the fully-qualified name of the BrokerService's Launch RPC.
	BrokerServiceLaunchProcedure = "/broker.v1.BrokerService/Launch"
	// BrokerServiceStopProcedure is the fully-qualified name of the BrokerService's Stop RPC.
	BrokerServiceStopProcedure = "/broker.v1.BrokerService/Stop"
	// BrokerServiceStartProcedure is the fully-qualified name of the BrokerService's Start RPC.
	BrokerServiceStartProcedure = "/broker.v1.BrokerService/Start"
	// BrokerServiceDownProcedure is the fully-qualified name of the BrokerService's Down RPC.
	BrokerServiceDownProcedure = "/broker.v1.BrokerService/Down"
	// BrokerServiceStatusProcedure is the fully-qualified name of the BrokerService's Status RPC.
	BrokerServiceStatusProcedure = "/broker.v1.BrokerService/Status"
	// BrokerServiceExecProcedure is the fully-qualified name of the BrokerService's Exec RPC.
	BrokerServiceExecProcedure = "/broker.v1.BrokerService/Exec"
	// BrokerServiceLogsProcedure is the fully-qualified name of the BrokerService's Logs RPC.
	BrokerServiceLogsProcedure = "/broker.v1.BrokerService/Logs"
	// BrokerServiceCancelJobProcedure is the fully-qualified name of the BrokerService's CancelJob RPC.
	BrokerServiceCancelJobProcedure = "/broker.v1.BrokerService/CancelJob"
)

// BrokerServiceClient is a client for the broker.v1.BrokerService service.
type BrokerServiceClient interface {
	Launch(context.Context, *connect.Request[brokerpb.LaunchRequest]) (*connect.Response[brokerpb.LaunchResponse], error)
	Stop(context.Context, *connect.Request[brokerpb.ClusterRequest]) (*connect.Response[brokerpb.ClusterResponse], error)
	Start(context.Context, *connect.Request[brokerpb.ClusterRequest]) (*connect.Response[brokerpb.ClusterResponse], error)
	Down(context.Context, *connect.Request[brokerpb.ClusterRequest]) (*connect.Response[brokerpb.ClusterResponse], error)
	Status(context.Context, *connect.Request[brokerpb.StatusRequest]) (*connect.Response[brokerpb.StatusResponse], error)
	Exec(context.Context, *connect.Request[brokerpb.ExecRequest]) (*connect.Response[brokerpb.ExecResponse], error)
	Logs(context.Context, *connect.Request[brokerpb.LogsRequest]) (*connect.ServerStreamForClient[brokerpb.LogsResponse], error)
	CancelJob(context.Context, *connect.Request[brokerpb.CancelJobRequest]) (*connect.Response[brokerpb.CancelJobResponse], error)
}

// NewBrokerServiceClient constructs a client for the broker.v1.BrokerService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBrokerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BrokerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	brokerServiceMethods := brokerpb.File_proto_broker_proto.Services().ByName("BrokerService").Methods()
	return &brokerServiceClient{
		launch: connect.NewClient[brokerpb.LaunchRequest, brokerpb.LaunchResponse](
			httpClient,
			baseURL+BrokerServiceLaunchProcedure,
			connect.WithSchema(brokerServiceMethods.ByName("Launch")),
			connect.WithClientOptions(opts...),
		),
		stop: connect.NewClient[brokerpb.ClusterRequest, brokerpb.ClusterResponse](
			httpClient,
			baseURL+BrokerServiceStopProcedure,
			connect.WithSchema(brokerServiceMethods.ByName("Stop")),
			connect.WithClientOptions(opts...),
		),
		start: connect.NewClient[brokerpb.ClusterRequest, brokerpb.ClusterResponse](
			httpClient,
			baseURL+BrokerServiceStartProcedure,
			connect.WithSchema(brokerServiceMethods.ByName("Start")),
			connect.WithClientOptions(opts...),
		),
		down: connect.NewClient[brokerpb.ClusterRequest, brokerpb.ClusterResponse](
			httpClient,
			baseURL+BrokerServiceDownProcedure,
			connect.WithSchema(brokerServiceMethods.ByName("Down")),
			connect.WithClientOptions(opts...),
		),
		status: connect.NewClient[brokerpb.StatusRequest, brokerpb.StatusResponse](
			httpClient,
			baseURL+BrokerServiceStatusProcedure,
			connect.WithSchema(brokerServiceMethods.ByName("Status")),
			connect.WithClientOptions(opts...),
		),
		exec: connect.NewClient[brokerpb.ExecRequest, brokerpb.ExecResponse](
			httpClient,
			baseURL+BrokerServiceExecProcedure,
			connect.WithSchema(brokerServiceMethods.ByName("Exec")),
			connect.WithClientOptions(opts...),
		),
		logs: connect.NewClient[brokerpb.LogsRequest, brokerpb.LogsResponse](
			httpClient,
			baseURL+BrokerServiceLogsProcedure,
			connect.WithSchema(brokerServiceMethods.ByName("Logs")),
			connect.WithClientOptions(opts...),
		),
		cancelJob: connect.NewClient[brokerpb.CancelJobRequest, brokerpb.CancelJobResponse](
			httpClient,
			baseURL+BrokerServiceCancelJobProcedure,
			connect.WithSchema(brokerServiceMethods.ByName("CancelJob")),
			connect.WithClientOptions(opts...),
		),
	}
}

// brokerServiceClient implements BrokerServiceClient.
type brokerServiceClient struct {
	launch    *connect.Client[brokerpb.LaunchRequest, brokerpb.LaunchResponse]
	stop      *connect.Client[brokerpb.ClusterRequest, brokerpb.ClusterResponse]
	start     *connect.Client[brokerpb.ClusterRequest, brokerpb.ClusterResponse]
	down      *connect.Client[brokerpb.ClusterRequest, brokerpb.ClusterResponse]
	status    *connect.Client[brokerpb.StatusRequest, brokerpb.StatusResponse]
	exec      *connect.Client[brokerpb.ExecRequest, brokerpb.ExecResponse]
	logs      *connect.Client[brokerpb.LogsRequest, brokerpb.LogsResponse]
	cancelJob *connect.Client[brokerpb.CancelJobRequest, brokerpb.CancelJobResponse]
}

// Launch calls broker.v1.BrokerService.Launch.
func (c *brokerServiceClient) Launch(ctx context.Context, req *connect.Request[brokerpb.LaunchRequest]) (*connect.Response[brokerpb.LaunchResponse], error) {
	return c.launch.CallUnary(ctx, req)
}

// Stop calls broker.v1.BrokerService.Stop.
func (c *brokerServiceClient) Stop(ctx context.Context, req *connect.Request[brokerpb.ClusterRequest]) (*connect.Response[brokerpb.ClusterResponse], error) {
	return c.stop.CallUnary(ctx, req)
}

// Start calls broker.v1.BrokerService.Start.
func (c *brokerServiceClient) Start(ctx context.Context, req *connect.Request[brokerpb.ClusterRequest]) (*connect.Response[brokerpb.ClusterResponse], error) {
	return c.start.CallUnary(ctx, req)
}

// Down calls broker.v1.BrokerService.Down.
func (c *brokerServiceClient) Down(ctx context.Context, req *connect.Request[brokerpb.ClusterRequest]) (*connect.Response[brokerpb.ClusterResponse], error) {
	return c.down.CallUnary(ctx, req)
}

// Status calls broker.v1.BrokerService.Status.
func (c *brokerServiceClient) Status(ctx context.Context, req *connect.Request[brokerpb.StatusRequest]) (*connect.Response[brokerpb.StatusResponse], error) {
	return c.status.CallUnary(ctx, req)
}

// Exec calls broker.v1.BrokerService.Exec.
func (c *brokerServiceClient) Exec(ctx context.Context, req *connect.Request[brokerpb.ExecRequest]) (*connect.Response[brokerpb.ExecResponse], error) {
	return c.exec.CallUnary(ctx, req)
}

// Logs calls broker.v1.BrokerService.Logs.
func (c *brokerServiceClient) Logs(ctx context.Context, req *connect.Request[brokerpb.LogsRequest]) (*connect.ServerStreamForClient[brokerpb.LogsResponse], error) {
	return c.logs.CallServerStream(ctx, req)
}

// CancelJob calls broker.v1.BrokerService.CancelJob.
func (c *brokerServiceClient) CancelJob(ctx context.Context, req *connect.Request[brokerpb.CancelJobRequest]) (*connect.Response[brokerpb.CancelJobResponse], error) {
	return c.cancelJob.CallUnary(ctx, req)
}

// BrokerServiceHandler is an implementation of the broker.v1.BrokerService service.
type BrokerServiceHandler interface {
	Launch(context.Context, *connect.Request[brokerpb.LaunchRequest]) (*connect.Response[brokerpb.LaunchResponse], error)
	Stop(context.Context, *connect.Request[brokerpb.ClusterRequest]) (*connect.Response[brokerpb.ClusterResponse], error)
	Start(context.Context, *connect.Request[brokerpb.ClusterRequest]) (*connect.Response[brokerpb.ClusterResponse], error)
	Down(context.Context, *connect.Request[brokerpb.ClusterRequest]) (*connect.Response[brokerpb.ClusterResponse], error)
	Status(context.Context, *connect.Request[brokerpb.StatusRequest]) (*connect.Response[brokerpb.StatusResponse], error)
	Exec(context.Context, *connect.Request[brokerpb.ExecRequest]) (*connect.Response[brokerpb.ExecResponse], error)
	Logs(context.Context, *connect.Request[brokerpb.LogsRequest], *connect.ServerStream[brokerpb.LogsResponse]) error
	CancelJob(context.Context, *connect.Request[brokerpb.CancelJobRequest]) (*connect.Response[brokerpb.CancelJobResponse], error)
}

// NewBrokerServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBrokerServiceHandler(svc BrokerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	brokerServiceMethods := brokerpb.File_proto_broker_proto.Services().ByName("BrokerService").Methods()
	brokerServiceLaunchHandler := connect.NewUnaryHandler(
		BrokerServiceLaunchProcedure,
		svc.Launch,
		connect.WithSchema(brokerServiceMethods.ByName("Launch")),
		connect.WithHandlerOptions(opts...),
	)
	brokerServiceStopHandler := connect.NewUnaryHandler(
		BrokerServiceStopProcedure,
		svc.Stop,
		connect.WithSchema(brokerServiceMethods.ByName("Stop")),
		connect.WithHandlerOptions(opts...),
	)
	brokerServiceStartHandler := connect.NewUnaryHandler(
		BrokerServiceStartProcedure,
		svc.Start,
		connect.WithSchema(brokerServiceMethods.ByName("Start")),
		connect.WithHandlerOptions(opts...),
	)
	brokerServiceDownHandler := connect.NewUnaryHandler(
		BrokerServiceDownProcedure,
		svc.Down,
		connect.WithSchema(brokerServiceMethods.ByName("Down")),
		connect.WithHandlerOptions(opts...),
	)
	brokerServiceStatusHandler := connect.NewUnaryHandler(
		BrokerServiceStatusProcedure,
		svc.Status,
		connect.WithSchema(brokerServiceMethods.ByName("Status")),
		connect.WithHandlerOptions(opts...),
	)
	brokerServiceExecHandler := connect.NewUnaryHandler(
		BrokerServiceExecProcedure,
		svc.Exec,
		connect.WithSchema(brokerServiceMethods.ByName("Exec")),
		connect.WithHandlerOptions(opts...),
	)
	brokerServiceLogsHandler := connect.NewServerStreamHandler(
		BrokerServiceLogsProcedure,
		svc.Logs,
		connect.WithSchema(brokerServiceMethods.ByName("Logs")),
		connect.WithHandlerOptions(opts...),
	)
	brokerServiceCancelJobHandler := connect.NewUnaryHandler(
		BrokerServiceCancelJobProcedure,
		svc.CancelJob,
		connect.WithSchema(brokerServiceMethods.ByName("CancelJob")),
		connect.WithHandlerOptions(opts...),
	)
	return "/broker.v1.BrokerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BrokerServiceLaunchProcedure:
			brokerServiceLaunchHandler.ServeHTTP(w, r)
		case BrokerServiceStopProcedure:
			brokerServiceStopHandler.ServeHTTP(w, r)
		case BrokerServiceStartProcedure:
			brokerServiceStartHandler.ServeHTTP(w, r)
		case BrokerServiceDownProcedure:
			brokerServiceDownHandler.ServeHTTP(w, r)
		case BrokerServiceStatusProcedure:
			brokerServiceStatusHandler.ServeHTTP(w, r)
		case BrokerServiceExecProcedure:
			brokerServiceExecHandler.ServeHTTP(w, r)
		case BrokerServiceLogsProcedure:
			brokerServiceLogsHandler.ServeHTTP(w, r)
		case BrokerServiceCancelJobProcedure:
			brokerServiceCancelJobHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBrokerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBrokerServiceHandler struct{}

func (UnimplementedBrokerServiceHandler) Launch(context.Context, *connect.Request[brokerpb.LaunchRequest]) (*connect.Response[brokerpb.LaunchResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("broker.v1.BrokerService.Launch is not implemented"))
}

func (UnimplementedBrokerServiceHandler) Stop(context.Context, *connect.Request[brokerpb.ClusterRequest]) (*connect.Response[brokerpb.ClusterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("broker.v1.BrokerService.Stop is not implemented"))
}

func (UnimplementedBrokerServiceHandler) Start(context.Context, *connect.Request[brokerpb.ClusterRequest]) (*connect.Response[brokerpb.ClusterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("broker.v1.BrokerService.Start is not implemented"))
}

func (UnimplementedBrokerServiceHandler) Down(context.Context, *connect.Request[brokerpb.ClusterRequest]) (*connect.Response[brokerpb.ClusterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("broker.v1.BrokerService.Down is not implemented"))
}

func (UnimplementedBrokerServiceHandler) Status(context.Context, *connect.Request[brokerpb.StatusRequest]) (*connect.Response[brokerpb.StatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("broker.v1.BrokerService.Status is not implemented"))
}

func (UnimplementedBrokerServiceHandler) Exec(context.Context, *connect.Request[brokerpb.ExecRequest]) (*connect.Response[brokerpb.ExecResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("broker.v1.BrokerService.Exec is not implemented"))
}

func (UnimplementedBrokerServiceHandler) Logs(context.Context, *connect.Request[brokerpb.LogsRequest], *connect.ServerStream[brokerpb.LogsResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("broker.v1.BrokerService.Logs is not implemented"))
}

func (UnimplementedBrokerServiceHandler) CancelJob(context.Context, *connect.Request[brokerpb.CancelJobRequest]) (*connect.Response[brokerpb.CancelJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("broker.v1.BrokerService.CancelJob is not implemented"))
}
