// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobState int32

const (
	JobState_JOB_STATE_UNSPECIFIED JobState = 0
	JobState_JOB_STATE_PULLING     JobState = 1
	JobState_JOB_STATE_SETUP       JobState = 2
	JobState_JOB_STATE_RUNNING     JobState = 3
	JobState_JOB_STATE_SUCCEEDED   JobState = 4
	JobState_JOB_STATE_FAILED      JobState = 5
	JobState_JOB_STATE_CANCELLED   JobState = 6
)

// Enum value maps for JobState.
var (
	JobState_name = map[int32]string{
		0: "JOB_STATE_UNSPECIFIED",
		1: "JOB_STATE_PULLING",
		2: "JOB_STATE_SETUP",
		3: "JOB_STATE_RUNNING",
		4: "JOB_STATE_SUCCEEDED",
		5: "JOB_STATE_FAILED",
		6: "JOB_STATE_CANCELLED",
	}
	JobState_value = map[string]int32{
		"JOB_STATE_UNSPECIFIED": 0,
		"JOB_STATE_PULLING":     1,
		"JOB_STATE_SETUP":       2,
		"JOB_STATE_RUNNING":     3,
		"JOB_STATE_SUCCEEDED":   4,
		"JOB_STATE_FAILED":      5,
		"JOB_STATE_CANCELLED":   6,
	}
)

func (x JobState) Enum() *JobState {
	p := new(JobState)
	*p = x
	return p
}

func (x JobState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_proto_enumTypes[0].Descriptor()
}

func (JobState) Type() protoreflect.EnumType {
	return &file_proto_agent_proto_enumTypes[0]
}

func (x JobState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobState.Descriptor instead.
func (JobState) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

// Envelope wraps all messages sent over the WebSocket tunnel.
// Each WebSocket frame is a single serialized Envelope.
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_Register
	//	*Envelope_Heartbeat
	//	*Envelope_LogBatch
	//	*Envelope_JobUpdate
	//	*Envelope_SshSession
	//	*Envelope_RegisterAck
	//	*Envelope_SubmitJob
	//	*Envelope_CancelJob
	//	*Envelope_TerminateNode
	//	*Envelope_SshSessionData
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetRegister() *Register {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *Envelope) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Envelope) GetLogBatch() *LogBatch {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_LogBatch); ok {
			return x.LogBatch
		}
	}
	return nil
}

func (x *Envelope) GetJobUpdate() *JobUpdate {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_JobUpdate); ok {
			return x.JobUpdate
		}
	}
	return nil
}

func (x *Envelope) GetSshSession() *SSHSession {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SshSession); ok {
			return x.SshSession
		}
	}
	return nil
}

func (x *Envelope) GetRegisterAck() *RegisterAck {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_RegisterAck); ok {
			return x.RegisterAck
		}
	}
	return nil
}

func (x *Envelope) GetSubmitJob() *SubmitJob {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SubmitJob); ok {
			return x.SubmitJob
		}
	}
	return nil
}

func (x *Envelope) GetCancelJob() *CancelJob {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_CancelJob); ok {
			return x.CancelJob
		}
	}
	return nil
}

func (x *Envelope) GetTerminateNode() *TerminateNode {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_TerminateNode); ok {
			return x.TerminateNode
		}
	}
	return nil
}

func (x *Envelope) GetSshSessionData() *SSHSessionData {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SshSessionData); ok {
			return x.SshSessionData
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_Register struct {
	// Agent -> Server
	Register *Register `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type Envelope_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type Envelope_LogBatch struct {
	LogBatch *LogBatch `protobuf:"bytes,3,opt,name=log_batch,json=logBatch,proto3,oneof"`
}

type Envelope_JobUpdate struct {
	JobUpdate *JobUpdate `protobuf:"bytes,4,opt,name=job_update,json=jobUpdate,proto3,oneof"`
}

type Envelope_SshSession struct {
	SshSession *SSHSession `protobuf:"bytes,10,opt,name=ssh_session,json=sshSession,proto3,oneof"`
}

type Envelope_RegisterAck struct {
	// Server -> Agent
	RegisterAck *RegisterAck `protobuf:"bytes,20,opt,name=register_ack,json=registerAck,proto3,oneof"`
}

type Envelope_SubmitJob struct {
	SubmitJob *SubmitJob `protobuf:"bytes,21,opt,name=submit_job,json=submitJob,proto3,oneof"`
}

type Envelope_CancelJob struct {
	CancelJob *CancelJob `protobuf:"bytes,22,opt,name=cancel_job,json=cancelJob,proto3,oneof"`
}

type Envelope_TerminateNode struct {
	TerminateNode *TerminateNode `protobuf:"bytes,23,opt,name=terminate_node,json=terminateNode,proto3,oneof"`
}

type Envelope_SshSessionData struct {
	SshSessionData *SSHSessionData `protobuf:"bytes,30,opt,name=ssh_session_data,json=sshSessionData,proto3,oneof"`
}

func (*Envelope_Register) isEnvelope_Payload() {}

func (*Envelope_Heartbeat) isEnvelope_Payload() {}

func (*Envelope_LogBatch) isEnvelope_Payload() {}

func (*Envelope_JobUpdate) isEnvelope_Payload() {}

func (*Envelope_SshSession) isEnvelope_Payload() {}

func (*Envelope_RegisterAck) isEnvelope_Payload() {}

func (*Envelope_SubmitJob) isEnvelope_Payload() {}

func (*Envelope_CancelJob) isEnvelope_Payload() {}

func (*Envelope_TerminateNode) isEnvelope_Payload() {}

func (*Envelope_SshSessionData) isEnvelope_Payload() {}

type Register struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ClusterName   string                 `protobuf:"bytes,2,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	NodeInfo      *NodeInfo              `protobuf:"bytes,4,opt,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Register) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Register) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *Register) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Register) GetNodeInfo() *NodeInfo {
	if x != nil {
		return x.NodeInfo
	}
	return nil
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	PublicIp      string                 `protobuf:"bytes,2,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`
	PrivateIp     string                 `protobuf:"bytes,3,opt,name=private_ip,json=privateIp,proto3" json:"private_ip,omitempty"`
	Os            string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`
	Cpus          int32                  `protobuf:"varint,6,opt,name=cpus,proto3" json:"cpus,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,7,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	DiskBytes     int64                  `protobuf:"varint,8,opt,name=disk_bytes,json=diskBytes,proto3" json:"disk_bytes,omitempty"`
	Gpus          []*GPUInfo             `protobuf:"bytes,9,rep,name=gpus,proto3" json:"gpus,omitempty"`
	SshPort       int32                  `protobuf:"varint,10,opt,name=ssh_port,json=sshPort,proto3" json:"ssh_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *NodeInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NodeInfo) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

func (x *NodeInfo) GetPrivateIp() string {
	if x != nil {
		return x.PrivateIp
	}
	return ""
}

func (x *NodeInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *NodeInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *NodeInfo) GetCpus() int32 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

func (x *NodeInfo) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *NodeInfo) GetDiskBytes() int64 {
	if x != nil {
		return x.DiskBytes
	}
	return 0
}

func (x *NodeInfo) GetGpus() []*GPUInfo {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *NodeInfo) GetSshPort() int32 {
	if x != nil {
		return x.SshPort
	}
	return 0
}

type GPUInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	Uuid          string                 `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Index         int32                  `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUInfo) Reset() {
	*x = GPUInfo{}
	mi := &file_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUInfo) ProtoMessage() {}

func (x *GPUInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUInfo.ProtoReflect.Descriptor instead.
func (*GPUInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *GPUInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GPUInfo) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *GPUInfo) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GPUInfo) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,2,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,3,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryPercent float64                `protobuf:"fixed64,4,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	DiskUsedBytes int64                  `protobuf:"varint,5,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	GpuMetrics    []*GPUMetrics          `protobuf:"bytes,6,rep,name=gpu_metrics,json=gpuMetrics,proto3" json:"gpu_metrics,omitempty"`
	RunningJobIds []string               `protobuf:"bytes,7,rep,name=running_job_ids,json=runningJobIds,proto3" json:"running_job_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Heartbeat) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *Heartbeat) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *Heartbeat) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *Heartbeat) GetDiskUsedBytes() int64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

func (x *Heartbeat) GetGpuMetrics() []*GPUMetrics {
	if x != nil {
		return x.GpuMetrics
	}
	return nil
}

func (x *Heartbeat) GetRunningJobIds() []string {
	if x != nil {
		return x.RunningJobIds
	}
	return nil
}

type GPUMetrics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Index              int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	UtilizationPercent float64                `protobuf:"fixed64,2,opt,name=utilization_percent,json=utilizationPercent,proto3" json:"utilization_percent,omitempty"`
	MemoryUsedBytes    int64                  `protobuf:"varint,3,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	TemperatureCelsius float64                `protobuf:"fixed64,4,opt,name=temperature_celsius,json=temperatureCelsius,proto3" json:"temperature_celsius,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GPUMetrics) Reset() {
	*x = GPUMetrics{}
	mi := &file_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUMetrics) ProtoMessage() {}

func (x *GPUMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUMetrics.ProtoReflect.Descriptor instead.
func (*GPUMetrics) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *GPUMetrics) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GPUMetrics) GetUtilizationPercent() float64 {
	if x != nil {
		return x.UtilizationPercent
	}
	return 0
}

func (x *GPUMetrics) GetMemoryUsedBytes() int64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *GPUMetrics) GetTemperatureCelsius() float64 {
	if x != nil {
		return x.TemperatureCelsius
	}
	return 0
}

type LogBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Entries       []*LogEntry            `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogBatch) Reset() {
	*x = LogBatch{}
	mi := &file_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogBatch) ProtoMessage() {}

func (x *LogBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogBatch.ProtoReflect.Descriptor instead.
func (*LogBatch) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *LogBatch) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *LogBatch) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type LogEntry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TimestampUnixNano int64                  `protobuf:"varint,1,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	Stream            string                 `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"` // "stdout" or "stderr"
	Data              []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *LogEntry) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *LogEntry) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *LogEntry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type JobUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State         JobState               `protobuf:"varint,2,opt,name=state,proto3,enum=broker.agent.v1.JobState" json:"state,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobUpdate) Reset() {
	*x = JobUpdate{}
	mi := &file_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobUpdate) ProtoMessage() {}

func (x *JobUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobUpdate.ProtoReflect.Descriptor instead.
func (*JobUpdate) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *JobUpdate) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobUpdate) GetState() JobState {
	if x != nil {
		return x.State
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *JobUpdate) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *JobUpdate) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// SSH session data flowing from agent to server (user -> agent -> server -> CLI).
type SSHSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Closed        bool                   `protobuf:"varint,3,opt,name=closed,proto3" json:"closed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHSession) Reset() {
	*x = SSHSession{}
	mi := &file_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHSession) ProtoMessage() {}

func (x *SSHSession) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHSession.ProtoReflect.Descriptor instead.
func (*SSHSession) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *SSHSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SSHSession) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SSHSession) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

type RegisterAck struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Accepted                 bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Error                    string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	HeartbeatIntervalSeconds int32                  `protobuf:"varint,3,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RegisterAck) Reset() {
	*x = RegisterAck{}
	mi := &file_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAck) ProtoMessage() {}

func (x *RegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAck.ProtoReflect.Descriptor instead.
func (*RegisterAck) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RegisterAck) GetHeartbeatIntervalSeconds() int32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

type SubmitJob struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	JobId string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Docker mode (host mode agent manages containers)
	Image   string            `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Command []string          `protobuf:"bytes,4,rep,name=command,proto3" json:"command,omitempty"`
	Env     map[string]string `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ports   []string          `protobuf:"bytes,6,rep,name=ports,proto3" json:"ports,omitempty"`
	GpuIds  []string          `protobuf:"bytes,7,rep,name=gpu_ids,json=gpuIds,proto3" json:"gpu_ids,omitempty"`
	// Direct exec mode (run mode agent inside container)
	SetupScript   string `protobuf:"bytes,8,opt,name=setup_script,json=setupScript,proto3" json:"setup_script,omitempty"`
	RunScript     string `protobuf:"bytes,9,opt,name=run_script,json=runScript,proto3" json:"run_script,omitempty"`
	Workdir       string `protobuf:"bytes,10,opt,name=workdir,proto3" json:"workdir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJob) Reset() {
	*x = SubmitJob{}
	mi := &file_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJob) ProtoMessage() {}

func (x *SubmitJob) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJob.ProtoReflect.Descriptor instead.
func (*SubmitJob) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *SubmitJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SubmitJob) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubmitJob) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *SubmitJob) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *SubmitJob) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *SubmitJob) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *SubmitJob) GetGpuIds() []string {
	if x != nil {
		return x.GpuIds
	}
	return nil
}

func (x *SubmitJob) GetSetupScript() string {
	if x != nil {
		return x.SetupScript
	}
	return ""
}

func (x *SubmitJob) GetRunScript() string {
	if x != nil {
		return x.RunScript
	}
	return ""
}

func (x *SubmitJob) GetWorkdir() string {
	if x != nil {
		return x.Workdir
	}
	return ""
}

type CancelJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJob) Reset() {
	*x = CancelJob{}
	mi := &file_proto_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJob) ProtoMessage() {}

func (x *CancelJob) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJob.ProtoReflect.Descriptor instead.
func (*CancelJob) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *CancelJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CancelJob) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type TerminateNode struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Reason             string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	GracePeriodSeconds int32                  `protobuf:"varint,2,opt,name=grace_period_seconds,json=gracePeriodSeconds,proto3" json:"grace_period_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TerminateNode) Reset() {
	*x = TerminateNode{}
	mi := &file_proto_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateNode) ProtoMessage() {}

func (x *TerminateNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateNode.ProtoReflect.Descriptor instead.
func (*TerminateNode) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{13}
}

func (x *TerminateNode) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *TerminateNode) GetGracePeriodSeconds() int32 {
	if x != nil {
		return x.GracePeriodSeconds
	}
	return 0
}

// SSH session data flowing from server to agent (CLI -> server -> agent -> user).
type SSHSessionData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Closed        bool                   `protobuf:"varint,3,opt,name=closed,proto3" json:"closed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHSessionData) Reset() {
	*x = SSHSessionData{}
	mi := &file_proto_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHSessionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHSessionData) ProtoMessage() {}

func (x *SSHSessionData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHSessionData.ProtoReflect.Descriptor instead.
func (*SSHSessionData) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{14}
}

func (x *SSHSessionData) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SSHSessionData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SSHSessionData) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\x0fbroker.agent.v1\"\x94\x05\n" +
	"\bEnvelope\x127\n" +
	"\bregister\x18\x01 \x01(\v2\x19.broker.agent.v1.RegisterH\x00R\bregister\x12:\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1a.broker.agent.v1.HeartbeatH\x00R\theartbeat\x128\n" +
	"\tlog_batch\x18\x03 \x01(\v2\x19.broker.agent.v1.LogBatchH\x00R\blogBatch\x12;\n" +
	"\n" +
	"job_update\x18\x04 \x01(\v2\x1a.broker.agent.v1.JobUpdateH\x00R\tjobUpdate\x12>\n" +
	"\vssh_session\x18\n" +
	" \x01(\v2\x1b.broker.agent.v1.SSHSessionH\x00R\n" +
	"sshSession\x12A\n" +
	"\fregister_ack\x18\x14 \x01(\v2\x1c.broker.agent.v1.RegisterAckH\x00R\vregisterAck\x12;\n" +
	"\n" +
	"submit_job\x18\x15 \x01(\v2\x1a.broker.agent.v1.SubmitJobH\x00R\tsubmitJob\x12;\n" +
	"\n" +
	"cancel_job\x18\x16 \x01(\v2\x1a.broker.agent.v1.CancelJobH\x00R\tcancelJob\x12G\n" +
	"\x0eterminate_node\x18\x17 \x01(\v2\x1e.broker.agent.v1.TerminateNodeH\x00R\rterminateNode\x12K\n" +
	"\x10ssh_session_data\x18\x1e \x01(\v2\x1f.broker.agent.v1.SSHSessionDataH\x00R\x0esshSessionDataB\t\n" +
	"\apayload\"\x94\x01\n" +
	"\bRegister\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12!\n" +
	"\fcluster_name\x18\x02 \x01(\tR\vclusterName\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x126\n" +
	"\tnode_info\x18\x04 \x01(\v2\x19.broker.agent.v1.NodeInfoR\bnodeInfo\"\xa5\x02\n" +
	"\bNodeInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1b\n" +
	"\tpublic_ip\x18\x02 \x01(\tR\bpublicIp\x12\x1d\n" +
	"\n" +
	"private_ip\x18\x03 \x01(\tR\tprivateIp\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\x12\x12\n" +
	"\x04cpus\x18\x06 \x01(\x05R\x04cpus\x12!\n" +
	"\fmemory_bytes\x18\a \x01(\x03R\vmemoryBytes\x12\x1d\n" +
	"\n" +
	"disk_bytes\x18\b \x01(\x03R\tdiskBytes\x12,\n" +
	"\x04gpus\x18\t \x03(\v2\x18.broker.agent.v1.GPUInfoR\x04gpus\x12\x19\n" +
	"\bssh_port\x18\n" +
	" \x01(\x05R\asshPort\"l\n" +
	"\aGPUInfo\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x03R\vmemoryBytes\x12\x12\n" +
	"\x04uuid\x18\x03 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05index\x18\x04 \x01(\x05R\x05index\"\xa1\x02\n" +
	"\tHeartbeat\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12%\n" +
	"\x0etimestamp_unix\x18\x02 \x01(\x03R\rtimestampUnix\x12\x1f\n" +
	"\vcpu_percent\x18\x03 \x01(\x01R\n" +
	"cpuPercent\x12%\n" +
	"\x0ememory_percent\x18\x04 \x01(\x01R\rmemoryPercent\x12&\n" +
	"\x0fdisk_used_bytes\x18\x05 \x01(\x03R\rdiskUsedBytes\x12<\n" +
	"\vgpu_metrics\x18\x06 \x03(\v2\x1b.broker.agent.v1.GPUMetricsR\n" +
	"gpuMetrics\x12&\n" +
	"\x0frunning_job_ids\x18\a \x03(\tR\rrunningJobIds\"\xb0\x01\n" +
	"\n" +
	"GPUMetrics\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12/\n" +
	"\x13utilization_percent\x18\x02 \x01(\x01R\x12utilizationPercent\x12*\n" +
	"\x11memory_used_bytes\x18\x03 \x01(\x03R\x0fmemoryUsedBytes\x12/\n" +
	"\x13temperature_celsius\x18\x04 \x01(\x01R\x12temperatureCelsius\"V\n" +
	"\bLogBatch\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x123\n" +
	"\aentries\x18\x02 \x03(\v2\x19.broker.agent.v1.LogEntryR\aentries\"f\n" +
	"\bLogEntry\x12.\n" +
	"\x13timestamp_unix_nano\x18\x01 \x01(\x03R\x11timestampUnixNano\x12\x16\n" +
	"\x06stream\x18\x02 \x01(\tR\x06stream\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\x86\x01\n" +
	"\tJobUpdate\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12/\n" +
	"\x05state\x18\x02 \x01(\x0e2\x19.broker.agent.v1.JobStateR\x05state\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"W\n" +
	"\n" +
	"SSHSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x16\n" +
	"\x06closed\x18\x03 \x01(\bR\x06closed\"}\n" +
	"\vRegisterAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x03 \x01(\x05R\x18heartbeatIntervalSeconds\"\xe0\x02\n" +
	"\tSubmitJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x18\n" +
	"\acommand\x18\x04 \x03(\tR\acommand\x125\n" +
	"\x03env\x18\x05 \x03(\v2#.broker.agent.v1.SubmitJob.EnvEntryR\x03env\x12\x14\n" +
	"\x05ports\x18\x06 \x03(\tR\x05ports\x12\x17\n" +
	"\agpu_ids\x18\a \x03(\tR\x06gpuIds\x12!\n" +
	"\fsetup_script\x18\b \x01(\tR\vsetupScript\x12\x1d\n" +
	"\n" +
	"run_script\x18\t \x01(\tR\trunScript\x12\x18\n" +
	"\aworkdir\x18\n" +
	" \x01(\tR\aworkdir\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"8\n" +
	"\tCancelJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"Y\n" +
	"\rTerminateNode\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x120\n" +
	"\x14grace_period_seconds\x18\x02 \x01(\x05R\x12gracePeriodSeconds\"[\n" +
	"\x0eSSHSessionData\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x16\n" +
	"\x06closed\x18\x03 \x01(\bR\x06closed*\xb0\x01\n" +
	"\bJobState\x12\x19\n" +
	"\x15JOB_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11JOB_STATE_PULLING\x10\x01\x12\x13\n" +
	"\x0fJOB_STATE_SETUP\x10\x02\x12\x15\n" +
	"\x11JOB_STATE_RUNNING\x10\x03\x12\x17\n" +
	"\x13JOB_STATE_SUCCEEDED\x10\x04\x12\x14\n" +
	"\x10JOB_STATE_FAILED\x10\x05\x12\x17\n" +
	"\x13JOB_STATE_CANCELLED\x10\x06B\x16Z\x14broker/proto/agentpbb\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_agent_proto_goTypes = []any{
	(JobState)(0),          // 0: broker.agent.v1.JobState
	(*Envelope)(nil),       // 1: broker.agent.v1.Envelope
	(*Register)(nil),       // 2: broker.agent.v1.Register
	(*NodeInfo)(nil),       // 3: broker.agent.v1.NodeInfo
	(*GPUInfo)(nil),        // 4: broker.agent.v1.GPUInfo
	(*Heartbeat)(nil),      // 5: broker.agent.v1.Heartbeat
	(*GPUMetrics)(nil),     // 6: broker.agent.v1.GPUMetrics
	(*LogBatch)(nil),       // 7: broker.agent.v1.LogBatch
	(*LogEntry)(nil),       // 8: broker.agent.v1.LogEntry
	(*JobUpdate)(nil),      // 9: broker.agent.v1.JobUpdate
	(*SSHSession)(nil),     // 10: broker.agent.v1.SSHSession
	(*RegisterAck)(nil),    // 11: broker.agent.v1.RegisterAck
	(*SubmitJob)(nil),      // 12: broker.agent.v1.SubmitJob
	(*CancelJob)(nil),      // 13: broker.agent.v1.CancelJob
	(*TerminateNode)(nil),  // 14: broker.agent.v1.TerminateNode
	(*SSHSessionData)(nil), // 15: broker.agent.v1.SSHSessionData
	nil,                    // 16: broker.agent.v1.SubmitJob.EnvEntry
}
var file_proto_agent_proto_depIdxs = []int32{
	2,  // 0: broker.agent.v1.Envelope.register:type_name -> broker.agent.v1.Register
	5,  // 1: broker.agent.v1.Envelope.heartbeat:type_name -> broker.agent.v1.Heartbeat
	7,  // 2: broker.agent.v1.Envelope.log_batch:type_name -> broker.agent.v1.LogBatch
	9,  // 3: broker.agent.v1.Envelope.job_update:type_name -> broker.agent.v1.JobUpdate
	10, // 4: broker.agent.v1.Envelope.ssh_session:type_name -> broker.agent.v1.SSHSession
	11, // 5: broker.agent.v1.Envelope.register_ack:type_name -> broker.agent.v1.RegisterAck
	12, // 6: broker.agent.v1.Envelope.submit_job:type_name -> broker.agent.v1.SubmitJob
	13, // 7: broker.agent.v1.Envelope.cancel_job:type_name -> broker.agent.v1.CancelJob
	14, // 8: broker.agent.v1.Envelope.terminate_node:type_name -> broker.agent.v1.TerminateNode
	15, // 9: broker.agent.v1.Envelope.ssh_session_data:type_name -> broker.agent.v1.SSHSessionData
	3,  // 10: broker.agent.v1.Register.node_info:type_name -> broker.agent.v1.NodeInfo
	4,  // 11: broker.agent.v1.NodeInfo.gpus:type_name -> broker.agent.v1.GPUInfo
	6,  // 12: broker.agent.v1.Heartbeat.gpu_metrics:type_name -> broker.agent.v1.GPUMetrics
	8,  // 13: broker.agent.v1.LogBatch.entries:type_name -> broker.agent.v1.LogEntry
	0,  // 14: broker.agent.v1.JobUpdate.state:type_name -> broker.agent.v1.JobState
	16, // 15: broker.agent.v1.SubmitJob.env:type_name -> broker.agent.v1.SubmitJob.EnvEntry
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	file_proto_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Register)(nil),
		(*Envelope_Heartbeat)(nil),
		(*Envelope_LogBatch)(nil),
		(*Envelope_JobUpdate)(nil),
		(*Envelope_SshSession)(nil),
		(*Envelope_RegisterAck)(nil),
		(*Envelope_SubmitJob)(nil),
		(*Envelope_CancelJob)(nil),
		(*Envelope_TerminateNode)(nil),
		(*Envelope_SshSessionData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		EnumInfos:         file_proto_agent_proto_enumTypes,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
