apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "broker.fullname" . }}
  labels:
    {{- include "broker.labels" . | nindent 4 }}
data:
  config.yaml: |
    api_server:
      http_port: {{ .Values.config.httpPort }}
      {{- if .Values.config.publicURL }}
      public_url: {{ .Values.config.publicURL | quote }}
      {{- end }}
    state:
      backend: {{ .Values.config.state.backend | quote }}
    analytics:
      backend: {{ .Values.config.analytics.backend | quote }}
