apiVersion: v1
kind: Secret
metadata:
  name: {{ include "broker.fullname" . }}
  labels:
    {{- include "broker.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and .Values.aws.enabled .Values.aws.accessKeyId }}
  aws-access-key-id: {{ .Values.aws.accessKeyId | b64enc | quote }}
  aws-secret-access-key: {{ .Values.aws.secretAccessKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.token }}
  broker-token: {{ .Values.auth.token | b64enc | quote }}
  {{- end }}
