// Code generated by hand; update when new instance families launch.
// Covers common GPU and general-purpose families used for AI workloads.

package aws

type InstanceSpec struct {
	InstanceType string
	VCPUs        int
	MemoryMB     int
	GPUCount     int
	GPUModel     string
	GPUMemoryMB  int
	Arch         string // x86_64 or arm64
}

var InstanceCatalog = map[string]InstanceSpec{
	// T3 family - general purpose (no GPU)
	"t3.micro":   {InstanceType: "t3.micro", VCPUs: 2, MemoryMB: 1024, Arch: "x86_64"},
	"t3.small":   {InstanceType: "t3.small", VCPUs: 2, MemoryMB: 2048, Arch: "x86_64"},
	"t3.medium":  {InstanceType: "t3.medium", VCPUs: 2, MemoryMB: 4096, Arch: "x86_64"},
	"t3.large":   {InstanceType: "t3.large", VCPUs: 2, MemoryMB: 8192, Arch: "x86_64"},
	"t3.xlarge":  {InstanceType: "t3.xlarge", VCPUs: 4, MemoryMB: 16384, Arch: "x86_64"},
	"t3.2xlarge": {InstanceType: "t3.2xlarge", VCPUs: 8, MemoryMB: 32768, Arch: "x86_64"},

	// G4dn family - NVIDIA T4 GPUs
	"g4dn.xlarge":   {InstanceType: "g4dn.xlarge", VCPUs: 4, MemoryMB: 16384, GPUCount: 1, GPUModel: "T4", GPUMemoryMB: 16384, Arch: "x86_64"},
	"g4dn.2xlarge":  {InstanceType: "g4dn.2xlarge", VCPUs: 8, MemoryMB: 32768, GPUCount: 1, GPUModel: "T4", GPUMemoryMB: 16384, Arch: "x86_64"},
	"g4dn.4xlarge":  {InstanceType: "g4dn.4xlarge", VCPUs: 16, MemoryMB: 65536, GPUCount: 1, GPUModel: "T4", GPUMemoryMB: 16384, Arch: "x86_64"},
	"g4dn.8xlarge":  {InstanceType: "g4dn.8xlarge", VCPUs: 32, MemoryMB: 131072, GPUCount: 1, GPUModel: "T4", GPUMemoryMB: 16384, Arch: "x86_64"},
	"g4dn.12xlarge": {InstanceType: "g4dn.12xlarge", VCPUs: 48, MemoryMB: 196608, GPUCount: 4, GPUModel: "T4", GPUMemoryMB: 16384, Arch: "x86_64"},
	"g4dn.16xlarge": {InstanceType: "g4dn.16xlarge", VCPUs: 64, MemoryMB: 262144, GPUCount: 1, GPUModel: "T4", GPUMemoryMB: 16384, Arch: "x86_64"},
	"g4dn.metal":    {InstanceType: "g4dn.metal", VCPUs: 96, MemoryMB: 393216, GPUCount: 8, GPUModel: "T4", GPUMemoryMB: 16384, Arch: "x86_64"},

	// G5 family - NVIDIA A10G GPUs
	"g5.xlarge":   {InstanceType: "g5.xlarge", VCPUs: 4, MemoryMB: 16384, GPUCount: 1, GPUModel: "A10G", GPUMemoryMB: 24576, Arch: "x86_64"},
	"g5.2xlarge":  {InstanceType: "g5.2xlarge", VCPUs: 8, MemoryMB: 32768, GPUCount: 1, GPUModel: "A10G", GPUMemoryMB: 24576, Arch: "x86_64"},
	"g5.4xlarge":  {InstanceType: "g5.4xlarge", VCPUs: 16, MemoryMB: 65536, GPUCount: 1, GPUModel: "A10G", GPUMemoryMB: 24576, Arch: "x86_64"},
	"g5.8xlarge":  {InstanceType: "g5.8xlarge", VCPUs: 32, MemoryMB: 131072, GPUCount: 1, GPUModel: "A10G", GPUMemoryMB: 24576, Arch: "x86_64"},
	"g5.12xlarge": {InstanceType: "g5.12xlarge", VCPUs: 48, MemoryMB: 196608, GPUCount: 4, GPUModel: "A10G", GPUMemoryMB: 24576, Arch: "x86_64"},
	"g5.16xlarge": {InstanceType: "g5.16xlarge", VCPUs: 64, MemoryMB: 262144, GPUCount: 1, GPUModel: "A10G", GPUMemoryMB: 24576, Arch: "x86_64"},
	"g5.24xlarge": {InstanceType: "g5.24xlarge", VCPUs: 96, MemoryMB: 393216, GPUCount: 4, GPUModel: "A10G", GPUMemoryMB: 24576, Arch: "x86_64"},
	"g5.48xlarge": {InstanceType: "g5.48xlarge", VCPUs: 192, MemoryMB: 786432, GPUCount: 8, GPUModel: "A10G", GPUMemoryMB: 24576, Arch: "x86_64"},

	// G6 family - NVIDIA L4 GPUs
	"g6.xlarge":   {InstanceType: "g6.xlarge", VCPUs: 4, MemoryMB: 16384, GPUCount: 1, GPUModel: "L4", GPUMemoryMB: 24576, Arch: "x86_64"},
	"g6.2xlarge":  {InstanceType: "g6.2xlarge", VCPUs: 8, MemoryMB: 32768, GPUCount: 1, GPUModel: "L4", GPUMemoryMB: 24576, Arch: "x86_64"},
	"g6.4xlarge":  {InstanceType: "g6.4xlarge", VCPUs: 16, MemoryMB: 65536, GPUCount: 1, GPUModel: "L4", GPUMemoryMB: 24576, Arch: "x86_64"},
	"g6.8xlarge":  {InstanceType: "g6.8xlarge", VCPUs: 32, MemoryMB: 131072, GPUCount: 1, GPUModel: "L4", GPUMemoryMB: 24576, Arch: "x86_64"},
	"g6.12xlarge": {InstanceType: "g6.12xlarge", VCPUs: 48, MemoryMB: 196608, GPUCount: 4, GPUModel: "L4", GPUMemoryMB: 24576, Arch: "x86_64"},
	"g6.16xlarge": {InstanceType: "g6.16xlarge", VCPUs: 64, MemoryMB: 262144, GPUCount: 1, GPUModel: "L4", GPUMemoryMB: 24576, Arch: "x86_64"},
	"g6.24xlarge": {InstanceType: "g6.24xlarge", VCPUs: 96, MemoryMB: 393216, GPUCount: 4, GPUModel: "L4", GPUMemoryMB: 24576, Arch: "x86_64"},
	"g6.48xlarge": {InstanceType: "g6.48xlarge", VCPUs: 192, MemoryMB: 786432, GPUCount: 8, GPUModel: "L4", GPUMemoryMB: 24576, Arch: "x86_64"},

	// P3 family - NVIDIA V100 GPUs
	"p3.2xlarge":  {InstanceType: "p3.2xlarge", VCPUs: 8, MemoryMB: 62464, GPUCount: 1, GPUModel: "V100", GPUMemoryMB: 16384, Arch: "x86_64"},
	"p3.8xlarge":  {InstanceType: "p3.8xlarge", VCPUs: 32, MemoryMB: 249856, GPUCount: 4, GPUModel: "V100", GPUMemoryMB: 16384, Arch: "x86_64"},
	"p3.16xlarge": {InstanceType: "p3.16xlarge", VCPUs: 64, MemoryMB: 499712, GPUCount: 8, GPUModel: "V100", GPUMemoryMB: 16384, Arch: "x86_64"},

	// P4d family - NVIDIA A100 GPUs
	"p4d.24xlarge":  {InstanceType: "p4d.24xlarge", VCPUs: 96, MemoryMB: 1179648, GPUCount: 8, GPUModel: "A100", GPUMemoryMB: 40960, Arch: "x86_64"},
	"p4de.24xlarge": {InstanceType: "p4de.24xlarge", VCPUs: 96, MemoryMB: 1179648, GPUCount: 8, GPUModel: "A100", GPUMemoryMB: 81920, Arch: "x86_64"},

	// P5 family - NVIDIA H100 GPUs
	"p5.48xlarge": {InstanceType: "p5.48xlarge", VCPUs: 192, MemoryMB: 2097152, GPUCount: 8, GPUModel: "H100", GPUMemoryMB: 81920, Arch: "x86_64"},
}

// GPUModelAliases maps alternative GPU names to the canonical names used in the catalog.
var GPUModelAliases = map[string]string{
	"NVIDIA T4":        "T4",
	"NVIDIA A10G":      "A10G",
	"NVIDIA L4":        "L4",
	"NVIDIA V100":      "V100",
	"NVIDIA A100":      "A100",
	"NVIDIA A100 80GB": "A100",
	"NVIDIA H100":      "H100",
	"NVIDIA H100 80GB": "H100",
	"TESLA T4":         "T4",
	"TESLA V100":       "V100",
	"TESLA V100-SXM2":  "V100",
	"TESLA V100S-PCIE": "V100",
}
