//go:build ignore

// This script queries the AWS EC2 DescribeInstanceTypes API and generates a
// Go source file containing instance specs for the catalog. Run it to refresh
// the hardcoded catalog data:
//
//   go run scripts/update-catalog.go > internal/provider/aws/catalog.go
//
// Requires AWS credentials with ec2:DescribeInstanceTypes permission.
//
// Note: The DescribeInstanceTypes API is slow to paginate across all instance
// types. This script filters to the instance families used in the existing
// hardcoded catalog (t3, g4dn, g5, g6, p3, p4d, p4de, p5). Add more families
// to the filter below if needed.

package main

import (
	"context"
	"fmt"
	"os"
	"sort"
	"strings"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/ec2"
	ec2types "github.com/aws/aws-sdk-go-v2/service/ec2/types"
)

var instanceFamilies = []string{
	"t3.*",
	"g4dn.*",
	"g5.*",
	"g6.*",
	"p3.*",
	"p4d.*",
	"p4de.*",
	"p5.*",
}

type spec struct {
	instanceType string
	vcpus        int
	memoryMB     int
	gpuCount     int
	gpuModel     string
	gpuMemoryMB  int
	arch         string
}

func main() {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()

	cfg, err := config.LoadDefaultConfig(ctx, config.WithRegion("us-east-1"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to load aws config: %v\n", err)
		os.Exit(1)
	}

	client := ec2.NewFromConfig(cfg)

	var specs []spec
	var nextToken *string

	for {
		input := &ec2.DescribeInstanceTypesInput{
			Filters: []ec2types.Filter{
				{
					Name:   aws.String("instance-type"),
					Values: instanceFamilies,
				},
			},
			NextToken: nextToken,
		}

		resp, err := client.DescribeInstanceTypes(ctx, input)
		if err != nil {
			fmt.Fprintf(os.Stderr, "api error: %v\n", err)
			os.Exit(1)
		}

		for _, it := range resp.InstanceTypes {
			s := spec{
				instanceType: string(it.InstanceType),
			}

			if it.VCpuInfo != nil && it.VCpuInfo.DefaultVCpus != nil {
				s.vcpus = int(*it.VCpuInfo.DefaultVCpus)
			}
			if it.MemoryInfo != nil && it.MemoryInfo.SizeInMiB != nil {
				s.memoryMB = int(*it.MemoryInfo.SizeInMiB)
			}

			if it.GpuInfo != nil && len(it.GpuInfo.Gpus) > 0 {
				gpu := it.GpuInfo.Gpus[0]
				if gpu.Count != nil {
					s.gpuCount = int(*gpu.Count)
				}
				if gpu.Name != nil {
					s.gpuModel = normalizeGPUModel(*gpu.Name)
				}
				if gpu.MemoryInfo != nil && gpu.MemoryInfo.SizeInMiB != nil {
					s.gpuMemoryMB = int(*gpu.MemoryInfo.SizeInMiB)
				}
			}

			s.arch = "x86_64"
			for _, arch := range it.ProcessorInfo.SupportedArchitectures {
				if arch == ec2types.ArchitectureTypeArm64 {
					s.arch = "arm64"
					break
				}
			}

			specs = append(specs, s)
		}

		fmt.Fprintf(os.Stderr, "fetched %d instance types so far...\n", len(specs))

		if resp.NextToken == nil {
			break
		}
		nextToken = resp.NextToken
	}

	generateGoFile(specs)
}

func normalizeGPUModel(name string) string {
	aliases := map[string]string{
		"T4":   "T4",
		"A10G": "A10G",
		"L4":   "L4",
		"V100": "V100",
		"A100": "A100",
		"H100": "H100",
	}

	upper := strings.ToUpper(name)
	for key, canonical := range aliases {
		if strings.Contains(upper, key) {
			return canonical
		}
	}
	return name
}

func generateGoFile(specs []spec) {
	sort.Slice(specs, func(i, j int) bool {
		return specs[i].instanceType < specs[j].instanceType
	})

	var b strings.Builder

	b.WriteString("// Code generated by scripts/update-catalog.go; DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("// Generated: %s\n", time.Now().UTC().Format(time.RFC3339)))
	b.WriteString(fmt.Sprintf("// Source: AWS EC2 DescribeInstanceTypes API, %d instance types\n\n", len(specs)))
	b.WriteString("package aws\n\n")
	b.WriteString("type InstanceSpec struct {\n")
	b.WriteString("\tInstanceType string\n")
	b.WriteString("\tVCPUs        int\n")
	b.WriteString("\tMemoryMB     int\n")
	b.WriteString("\tGPUCount     int\n")
	b.WriteString("\tGPUModel     string\n")
	b.WriteString("\tGPUMemoryMB  int\n")
	b.WriteString("\tArch         string // x86_64 or arm64\n")
	b.WriteString("}\n\n")

	b.WriteString("var InstanceCatalog = map[string]InstanceSpec{\n")
	for _, s := range specs {
		b.WriteString(fmt.Sprintf("\t%q: {InstanceType: %q, VCPUs: %d, MemoryMB: %d",
			s.instanceType, s.instanceType, s.vcpus, s.memoryMB))
		if s.gpuCount > 0 {
			b.WriteString(fmt.Sprintf(", GPUCount: %d, GPUModel: %q, GPUMemoryMB: %d",
				s.gpuCount, s.gpuModel, s.gpuMemoryMB))
		}
		b.WriteString(fmt.Sprintf(", Arch: %q},\n", s.arch))
	}
	b.WriteString("}\n\n")

	b.WriteString("var GPUModelAliases = map[string]string{\n")
	aliases := map[string]string{
		"NVIDIA T4":        "T4",
		"NVIDIA A10G":      "A10G",
		"NVIDIA L4":        "L4",
		"NVIDIA V100":      "V100",
		"NVIDIA A100":      "A100",
		"NVIDIA A100 80GB": "A100",
		"NVIDIA H100":      "H100",
		"NVIDIA H100 80GB": "H100",
		"TESLA T4":         "T4",
		"TESLA V100":       "V100",
	}
	keys := make([]string, 0, len(aliases))
	for k := range aliases {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		b.WriteString(fmt.Sprintf("\t%q: %q,\n", k, aliases[k]))
	}
	b.WriteString("}\n")

	fmt.Print(b.String())
}
