// This script queries the AWS Pricing API and generates a Go source file
// containing on-demand pricing for all EC2 instance types. Run it before
// release to bake in current prices:
//
//   go run scripts/update-pricing.go > internal/provider/aws/pricing_data.go
//
// Requires AWS credentials with pricing:GetProducts permission.
// The Pricing API is only available in us-east-1.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/pricing"
	"github.com/aws/aws-sdk-go-v2/service/pricing/types"
)

func main() {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()

	cfg, err := config.LoadDefaultConfig(ctx, config.WithRegion("us-east-1"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to load aws config: %v\n", err)
		os.Exit(1)
	}

	client := pricing.NewFromConfig(cfg)

	prices := map[string]float64{}
	var nextToken *string

	for {
		resp, err := client.GetProducts(ctx, &pricing.GetProductsInput{
			ServiceCode: aws.String("AmazonEC2"),
			Filters: []types.Filter{
				{Field: aws.String("operatingSystem"), Type: types.FilterTypeTermMatch, Value: aws.String("Linux")},
				{Field: aws.String("tenancy"), Type: types.FilterTypeTermMatch, Value: aws.String("Shared")},
				{Field: aws.String("preInstalledSw"), Type: types.FilterTypeTermMatch, Value: aws.String("NA")},
				{Field: aws.String("capacitystatus"), Type: types.FilterTypeTermMatch, Value: aws.String("Used")},
				{Field: aws.String("location"), Type: types.FilterTypeTermMatch, Value: aws.String("US East (N. Virginia)")},
			},
			NextToken: nextToken,
		})
		if err != nil {
			fmt.Fprintf(os.Stderr, "api error: %v\n", err)
			os.Exit(1)
		}

		for _, priceJSON := range resp.PriceList {
			instanceType, hourlyUSD := parseProduct(priceJSON)
			if instanceType != "" && hourlyUSD > 0 {
				prices[instanceType] = hourlyUSD
			}
		}

		fmt.Fprintf(os.Stderr, "fetched %d instance types so far...\n", len(prices))

		if resp.NextToken == nil {
			break
		}
		nextToken = resp.NextToken
	}

	generateGoFile(prices)
}

func parseProduct(raw string) (string, float64) {
	var product map[string]interface{}
	if err := json.Unmarshal([]byte(raw), &product); err != nil {
		return "", 0
	}

	attrs, ok := product["product"].(map[string]interface{})
	if !ok {
		return "", 0
	}
	attributes, ok := attrs["attributes"].(map[string]interface{})
	if !ok {
		return "", 0
	}

	instanceType, _ := attributes["instanceType"].(string)
	if instanceType == "" {
		return "", 0
	}

	terms, ok := product["terms"].(map[string]interface{})
	if !ok {
		return "", 0
	}
	onDemand, ok := terms["OnDemand"].(map[string]interface{})
	if !ok {
		return "", 0
	}

	for _, term := range onDemand {
		termMap, ok := term.(map[string]interface{})
		if !ok {
			continue
		}
		priceDimensions, ok := termMap["priceDimensions"].(map[string]interface{})
		if !ok {
			continue
		}
		for _, dim := range priceDimensions {
			dimMap, ok := dim.(map[string]interface{})
			if !ok {
				continue
			}
			pricePerUnit, ok := dimMap["pricePerUnit"].(map[string]interface{})
			if !ok {
				continue
			}
			usdStr, ok := pricePerUnit["USD"].(string)
			if !ok {
				continue
			}
			var usd float64
			fmt.Sscanf(usdStr, "%f", &usd)
			if usd > 0 {
				return instanceType, usd
			}
		}
	}

	return instanceType, 0
}

func generateGoFile(prices map[string]float64) {
	types := make([]string, 0, len(prices))
	for t := range prices {
		types = append(types, t)
	}
	sort.Strings(types)

	var b strings.Builder

	b.WriteString("// Code generated by scripts/update-pricing.go; DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("// Generated: %s\n", time.Now().UTC().Format(time.RFC3339)))
	b.WriteString(fmt.Sprintf("// Source: AWS Pricing API (us-east-1), %d instance types\n\n", len(types)))
	b.WriteString("package aws\n\n")
	b.WriteString("// OnDemandPricing maps EC2 instance types to their hourly on-demand price in USD.\n")
	b.WriteString("// Spot prices are typically 60-70%% cheaper; multiply by 0.35 for a rough estimate.\n")
	b.WriteString("var OnDemandPricing = map[string]float64{\n")

	for _, t := range types {
		b.WriteString(fmt.Sprintf("\t%q: %.4f,\n", t, prices[t]))
	}

	b.WriteString("}\n")

	fmt.Print(b.String())
}
