// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/broker.proto

package brokerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Workdir       string                 `protobuf:"bytes,2,opt,name=workdir,proto3" json:"workdir,omitempty"`
	NumNodes      int32                  `protobuf:"varint,3,opt,name=num_nodes,json=numNodes,proto3" json:"num_nodes,omitempty"`
	Resources     *Resources             `protobuf:"bytes,4,opt,name=resources,proto3" json:"resources,omitempty"`
	Envs          map[string]string      `protobuf:"bytes,5,rep,name=envs,proto3" json:"envs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Setup         string                 `protobuf:"bytes,6,opt,name=setup,proto3" json:"setup,omitempty"`
	Run           string                 `protobuf:"bytes,7,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskSpec) Reset() {
	*x = TaskSpec{}
	mi := &file_proto_broker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSpec) ProtoMessage() {}

func (x *TaskSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSpec.ProtoReflect.Descriptor instead.
func (*TaskSpec) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{0}
}

func (x *TaskSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskSpec) GetWorkdir() string {
	if x != nil {
		return x.Workdir
	}
	return ""
}

func (x *TaskSpec) GetNumNodes() int32 {
	if x != nil {
		return x.NumNodes
	}
	return 0
}

func (x *TaskSpec) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *TaskSpec) GetEnvs() map[string]string {
	if x != nil {
		return x.Envs
	}
	return nil
}

func (x *TaskSpec) GetSetup() string {
	if x != nil {
		return x.Setup
	}
	return ""
}

func (x *TaskSpec) GetRun() string {
	if x != nil {
		return x.Run
	}
	return ""
}

type Resources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cloud         string                 `protobuf:"bytes,1,opt,name=cloud,proto3" json:"cloud,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Zone          string                 `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`
	Accelerators  string                 `protobuf:"bytes,4,opt,name=accelerators,proto3" json:"accelerators,omitempty"`
	Cpus          string                 `protobuf:"bytes,5,opt,name=cpus,proto3" json:"cpus,omitempty"`
	Memory        string                 `protobuf:"bytes,6,opt,name=memory,proto3" json:"memory,omitempty"`
	InstanceType  string                 `protobuf:"bytes,7,opt,name=instance_type,json=instanceType,proto3" json:"instance_type,omitempty"`
	UseSpot       bool                   `protobuf:"varint,8,opt,name=use_spot,json=useSpot,proto3" json:"use_spot,omitempty"`
	DiskSizeGb    int32                  `protobuf:"varint,9,opt,name=disk_size_gb,json=diskSizeGb,proto3" json:"disk_size_gb,omitempty"`
	Ports         []string               `protobuf:"bytes,10,rep,name=ports,proto3" json:"ports,omitempty"`
	ImageId       string                 `protobuf:"bytes,11,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resources) Reset() {
	*x = Resources{}
	mi := &file_proto_broker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{1}
}

func (x *Resources) GetCloud() string {
	if x != nil {
		return x.Cloud
	}
	return ""
}

func (x *Resources) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Resources) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *Resources) GetAccelerators() string {
	if x != nil {
		return x.Accelerators
	}
	return ""
}

func (x *Resources) GetCpus() string {
	if x != nil {
		return x.Cpus
	}
	return ""
}

func (x *Resources) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *Resources) GetInstanceType() string {
	if x != nil {
		return x.InstanceType
	}
	return ""
}

func (x *Resources) GetUseSpot() bool {
	if x != nil {
		return x.UseSpot
	}
	return false
}

func (x *Resources) GetDiskSizeGb() int32 {
	if x != nil {
		return x.DiskSizeGb
	}
	return 0
}

func (x *Resources) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *Resources) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

type LaunchRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Task                  *TaskSpec              `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	ClusterName           string                 `protobuf:"bytes,2,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	RetryUntilUp          bool                   `protobuf:"varint,3,opt,name=retry_until_up,json=retryUntilUp,proto3" json:"retry_until_up,omitempty"`
	IdleMinutesToAutostop int32                  `protobuf:"varint,4,opt,name=idle_minutes_to_autostop,json=idleMinutesToAutostop,proto3" json:"idle_minutes_to_autostop,omitempty"`
	Dryrun                bool                   `protobuf:"varint,5,opt,name=dryrun,proto3" json:"dryrun,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *LaunchRequest) Reset() {
	*x = LaunchRequest{}
	mi := &file_proto_broker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchRequest) ProtoMessage() {}

func (x *LaunchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchRequest.ProtoReflect.Descriptor instead.
func (*LaunchRequest) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{2}
}

func (x *LaunchRequest) GetTask() *TaskSpec {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *LaunchRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *LaunchRequest) GetRetryUntilUp() bool {
	if x != nil {
		return x.RetryUntilUp
	}
	return false
}

func (x *LaunchRequest) GetIdleMinutesToAutostop() int32 {
	if x != nil {
		return x.IdleMinutesToAutostop
	}
	return 0
}

func (x *LaunchRequest) GetDryrun() bool {
	if x != nil {
		return x.Dryrun
	}
	return false
}

type LaunchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterName   string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	HeadIp        string                 `protobuf:"bytes,3,opt,name=head_ip,json=headIp,proto3" json:"head_ip,omitempty"`
	InstanceType  string                 `protobuf:"bytes,4,opt,name=instance_type,json=instanceType,proto3" json:"instance_type,omitempty"`
	HourlyPrice   float64                `protobuf:"fixed64,5,opt,name=hourly_price,json=hourlyPrice,proto3" json:"hourly_price,omitempty"`
	Region        string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchResponse) Reset() {
	*x = LaunchResponse{}
	mi := &file_proto_broker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchResponse) ProtoMessage() {}

func (x *LaunchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchResponse.ProtoReflect.Descriptor instead.
func (*LaunchResponse) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{3}
}

func (x *LaunchResponse) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *LaunchResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *LaunchResponse) GetHeadIp() string {
	if x != nil {
		return x.HeadIp
	}
	return ""
}

func (x *LaunchResponse) GetInstanceType() string {
	if x != nil {
		return x.InstanceType
	}
	return ""
}

func (x *LaunchResponse) GetHourlyPrice() float64 {
	if x != nil {
		return x.HourlyPrice
	}
	return 0
}

func (x *LaunchResponse) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type ClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterName   string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterRequest) Reset() {
	*x = ClusterRequest{}
	mi := &file_proto_broker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterRequest) ProtoMessage() {}

func (x *ClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterRequest.ProtoReflect.Descriptor instead.
func (*ClusterRequest) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{4}
}

func (x *ClusterRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

type ClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterName   string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterResponse) Reset() {
	*x = ClusterResponse{}
	mi := &file_proto_broker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterResponse) ProtoMessage() {}

func (x *ClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterResponse.ProtoReflect.Descriptor instead.
func (*ClusterResponse) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{5}
}

func (x *ClusterResponse) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *ClusterResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterNames  []string               `protobuf:"bytes,1,rep,name=cluster_names,json=clusterNames,proto3" json:"cluster_names,omitempty"`
	Refresh       bool                   `protobuf:"varint,2,opt,name=refresh,proto3" json:"refresh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_broker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{6}
}

func (x *StatusRequest) GetClusterNames() []string {
	if x != nil {
		return x.ClusterNames
	}
	return nil
}

func (x *StatusRequest) GetRefresh() bool {
	if x != nil {
		return x.Refresh
	}
	return false
}

type ClusterInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Cloud         string                 `protobuf:"bytes,3,opt,name=cloud,proto3" json:"cloud,omitempty"`
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	Resources     string                 `protobuf:"bytes,5,opt,name=resources,proto3" json:"resources,omitempty"`
	HeadIp        string                 `protobuf:"bytes,6,opt,name=head_ip,json=headIp,proto3" json:"head_ip,omitempty"`
	NumNodes      int32                  `protobuf:"varint,7,opt,name=num_nodes,json=numNodes,proto3" json:"num_nodes,omitempty"`
	LaunchedAt    string                 `protobuf:"bytes,8,opt,name=launched_at,json=launchedAt,proto3" json:"launched_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterInfo) Reset() {
	*x = ClusterInfo{}
	mi := &file_proto_broker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterInfo) ProtoMessage() {}

func (x *ClusterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterInfo.ProtoReflect.Descriptor instead.
func (*ClusterInfo) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{7}
}

func (x *ClusterInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClusterInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ClusterInfo) GetCloud() string {
	if x != nil {
		return x.Cloud
	}
	return ""
}

func (x *ClusterInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ClusterInfo) GetResources() string {
	if x != nil {
		return x.Resources
	}
	return ""
}

func (x *ClusterInfo) GetHeadIp() string {
	if x != nil {
		return x.HeadIp
	}
	return ""
}

func (x *ClusterInfo) GetNumNodes() int32 {
	if x != nil {
		return x.NumNodes
	}
	return 0
}

func (x *ClusterInfo) GetLaunchedAt() string {
	if x != nil {
		return x.LaunchedAt
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clusters      []*ClusterInfo         `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_broker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{8}
}

func (x *StatusResponse) GetClusters() []*ClusterInfo {
	if x != nil {
		return x.Clusters
	}
	return nil
}

type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterName   string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Task          *TaskSpec              `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_proto_broker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{9}
}

func (x *ExecRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *ExecRequest) GetTask() *TaskSpec {
	if x != nil {
		return x.Task
	}
	return nil
}

type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_proto_broker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{10}
}

func (x *ExecResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type LogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterName   string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Follow        bool                   `protobuf:"varint,3,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_proto_broker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{11}
}

func (x *LogsRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *LogsRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *LogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type LogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsResponse) Reset() {
	*x = LogsResponse{}
	mi := &file_proto_broker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsResponse) ProtoMessage() {}

func (x *LogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsResponse.ProtoReflect.Descriptor instead.
func (*LogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{12}
}

func (x *LogsResponse) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

type CancelJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterName   string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	JobIds        []string               `protobuf:"bytes,2,rep,name=job_ids,json=jobIds,proto3" json:"job_ids,omitempty"`
	All           bool                   `protobuf:"varint,3,opt,name=all,proto3" json:"all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobRequest) Reset() {
	*x = CancelJobRequest{}
	mi := &file_proto_broker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobRequest) ProtoMessage() {}

func (x *CancelJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobRequest.ProtoReflect.Descriptor instead.
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{13}
}

func (x *CancelJobRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *CancelJobRequest) GetJobIds() []string {
	if x != nil {
		return x.JobIds
	}
	return nil
}

func (x *CancelJobRequest) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

type CancelJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobResponse) Reset() {
	*x = CancelJobResponse{}
	mi := &file_proto_broker_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobResponse) ProtoMessage() {}

func (x *CancelJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobResponse.ProtoReflect.Descriptor instead.
func (*CancelJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{14}
}

var File_proto_broker_proto protoreflect.FileDescriptor

const file_proto_broker_proto_rawDesc = "" +
	"\n" +
	"\x12proto/broker.proto\x12\tbroker.v1\"\x9d\x02\n" +
	"\bTaskSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aworkdir\x18\x02 \x01(\tR\aworkdir\x12\x1b\n" +
	"\tnum_nodes\x18\x03 \x01(\x05R\bnumNodes\x122\n" +
	"\tresources\x18\x04 \x01(\v2\x14.broker.v1.ResourcesR\tresources\x121\n" +
	"\x04envs\x18\x05 \x03(\v2\x1d.broker.v1.TaskSpec.EnvsEntryR\x04envs\x12\x14\n" +
	"\x05setup\x18\x06 \x01(\tR\x05setup\x12\x10\n" +
	"\x03run\x18\a \x01(\tR\x03run\x1a7\n" +
	"\tEnvsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb0\x02\n" +
	"\tResources\x12\x14\n" +
	"\x05cloud\x18\x01 \x01(\tR\x05cloud\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x12\n" +
	"\x04zone\x18\x03 \x01(\tR\x04zone\x12\"\n" +
	"\faccelerators\x18\x04 \x01(\tR\faccelerators\x12\x12\n" +
	"\x04cpus\x18\x05 \x01(\tR\x04cpus\x12\x16\n" +
	"\x06memory\x18\x06 \x01(\tR\x06memory\x12#\n" +
	"\rinstance_type\x18\a \x01(\tR\finstanceType\x12\x19\n" +
	"\buse_spot\x18\b \x01(\bR\auseSpot\x12 \n" +
	"\fdisk_size_gb\x18\t \x01(\x05R\n" +
	"diskSizeGb\x12\x14\n" +
	"\x05ports\x18\n" +
	" \x03(\tR\x05ports\x12\x19\n" +
	"\bimage_id\x18\v \x01(\tR\aimageId\"\xd2\x01\n" +
	"\rLaunchRequest\x12'\n" +
	"\x04task\x18\x01 \x01(\v2\x13.broker.v1.TaskSpecR\x04task\x12!\n" +
	"\fcluster_name\x18\x02 \x01(\tR\vclusterName\x12$\n" +
	"\x0eretry_until_up\x18\x03 \x01(\bR\fretryUntilUp\x127\n" +
	"\x18idle_minutes_to_autostop\x18\x04 \x01(\x05R\x15idleMinutesToAutostop\x12\x16\n" +
	"\x06dryrun\x18\x05 \x01(\bR\x06dryrun\"\xc3\x01\n" +
	"\x0eLaunchResponse\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x17\n" +
	"\ahead_ip\x18\x03 \x01(\tR\x06headIp\x12#\n" +
	"\rinstance_type\x18\x04 \x01(\tR\finstanceType\x12!\n" +
	"\fhourly_price\x18\x05 \x01(\x01R\vhourlyPrice\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region\"3\n" +
	"\x0eClusterRequest\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\"L\n" +
	"\x0fClusterResponse\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"N\n" +
	"\rStatusRequest\x12#\n" +
	"\rcluster_names\x18\x01 \x03(\tR\fclusterNames\x12\x18\n" +
	"\arefresh\x18\x02 \x01(\bR\arefresh\"\xdc\x01\n" +
	"\vClusterInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05cloud\x18\x03 \x01(\tR\x05cloud\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x1c\n" +
	"\tresources\x18\x05 \x01(\tR\tresources\x12\x17\n" +
	"\ahead_ip\x18\x06 \x01(\tR\x06headIp\x12\x1b\n" +
	"\tnum_nodes\x18\a \x01(\x05R\bnumNodes\x12\x1f\n" +
	"\vlaunched_at\x18\b \x01(\tR\n" +
	"launchedAt\"D\n" +
	"\x0eStatusResponse\x122\n" +
	"\bclusters\x18\x01 \x03(\v2\x16.broker.v1.ClusterInfoR\bclusters\"Y\n" +
	"\vExecRequest\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12'\n" +
	"\x04task\x18\x02 \x01(\v2\x13.broker.v1.TaskSpecR\x04task\"%\n" +
	"\fExecResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"_\n" +
	"\vLogsRequest\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06follow\x18\x03 \x01(\bR\x06follow\"\"\n" +
	"\fLogsResponse\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line\"`\n" +
	"\x10CancelJobRequest\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12\x17\n" +
	"\ajob_ids\x18\x02 \x03(\tR\x06jobIds\x12\x10\n" +
	"\x03all\x18\x03 \x01(\bR\x03all\"\x13\n" +
	"\x11CancelJobResponse2\x87\x04\n" +
	"\rBrokerService\x12=\n" +
	"\x06Launch\x12\x18.broker.v1.LaunchRequest\x1a\x19.broker.v1.LaunchResponse\x12=\n" +
	"\x04Stop\x12\x19.broker.v1.ClusterRequest\x1a\x1a.broker.v1.ClusterResponse\x12>\n" +
	"\x05Start\x12\x19.broker.v1.ClusterRequest\x1a\x1a.broker.v1.ClusterResponse\x12=\n" +
	"\x04Down\x12\x19.broker.v1.ClusterRequest\x1a\x1a.broker.v1.ClusterResponse\x12=\n" +
	"\x06Status\x12\x18.broker.v1.StatusRequest\x1a\x19.broker.v1.StatusResponse\x127\n" +
	"\x04Exec\x12\x16.broker.v1.ExecRequest\x1a\x17.broker.v1.ExecResponse\x129\n" +
	"\x04Logs\x12\x16.broker.v1.LogsRequest\x1a\x17.broker.v1.LogsResponse0\x01\x12F\n" +
	"\tCancelJob\x12\x1b.broker.v1.CancelJobRequest\x1a\x1c.broker.v1.CancelJobResponseB\x17Z\x15broker/proto/brokerpbb\x06proto3"

var (
	file_proto_broker_proto_rawDescOnce sync.Once
	file_proto_broker_proto_rawDescData []byte
)

func file_proto_broker_proto_rawDescGZIP() []byte {
	file_proto_broker_proto_rawDescOnce.Do(func() {
		file_proto_broker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_broker_proto_rawDesc), len(file_proto_broker_proto_rawDesc)))
	})
	return file_proto_broker_proto_rawDescData
}

var file_proto_broker_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_broker_proto_goTypes = []any{
	(*TaskSpec)(nil),          // 0: broker.v1.TaskSpec
	(*Resources)(nil),         // 1: broker.v1.Resources
	(*LaunchRequest)(nil),     // 2: broker.v1.LaunchRequest
	(*LaunchResponse)(nil),    // 3: broker.v1.LaunchResponse
	(*ClusterRequest)(nil),    // 4: broker.v1.ClusterRequest
	(*ClusterResponse)(nil),   // 5: broker.v1.ClusterResponse
	(*StatusRequest)(nil),     // 6: broker.v1.StatusRequest
	(*ClusterInfo)(nil),       // 7: broker.v1.ClusterInfo
	(*StatusResponse)(nil),    // 8: broker.v1.StatusResponse
	(*ExecRequest)(nil),       // 9: broker.v1.ExecRequest
	(*ExecResponse)(nil),      // 10: broker.v1.ExecResponse
	(*LogsRequest)(nil),       // 11: broker.v1.LogsRequest
	(*LogsResponse)(nil),      // 12: broker.v1.LogsResponse
	(*CancelJobRequest)(nil),  // 13: broker.v1.CancelJobRequest
	(*CancelJobResponse)(nil), // 14: broker.v1.CancelJobResponse
	nil,                       // 15: broker.v1.TaskSpec.EnvsEntry
}
var file_proto_broker_proto_depIdxs = []int32{
	1,  // 0: broker.v1.TaskSpec.resources:type_name -> broker.v1.Resources
	15, // 1: broker.v1.TaskSpec.envs:type_name -> broker.v1.TaskSpec.EnvsEntry
	0,  // 2: broker.v1.LaunchRequest.task:type_name -> broker.v1.TaskSpec
	7,  // 3: broker.v1.StatusResponse.clusters:type_name -> broker.v1.ClusterInfo
	0,  // 4: broker.v1.ExecRequest.task:type_name -> broker.v1.TaskSpec
	2,  // 5: broker.v1.BrokerService.Launch:input_type -> broker.v1.LaunchRequest
	4,  // 6: broker.v1.BrokerService.Stop:input_type -> broker.v1.ClusterRequest
	4,  // 7: broker.v1.BrokerService.Start:input_type -> broker.v1.ClusterRequest
	4,  // 8: broker.v1.BrokerService.Down:input_type -> broker.v1.ClusterRequest
	6,  // 9: broker.v1.BrokerService.Status:input_type -> broker.v1.StatusRequest
	9,  // 10: broker.v1.BrokerService.Exec:input_type -> broker.v1.ExecRequest
	11, // 11: broker.v1.BrokerService.Logs:input_type -> broker.v1.LogsRequest
	13, // 12: broker.v1.BrokerService.CancelJob:input_type -> broker.v1.CancelJobRequest
	3,  // 13: broker.v1.BrokerService.Launch:output_type -> broker.v1.LaunchResponse
	5,  // 14: broker.v1.BrokerService.Stop:output_type -> broker.v1.ClusterResponse
	5,  // 15: broker.v1.BrokerService.Start:output_type -> broker.v1.ClusterResponse
	5,  // 16: broker.v1.BrokerService.Down:output_type -> broker.v1.ClusterResponse
	8,  // 17: broker.v1.BrokerService.Status:output_type -> broker.v1.StatusResponse
	10, // 18: broker.v1.BrokerService.Exec:output_type -> broker.v1.ExecResponse
	12, // 19: broker.v1.BrokerService.Logs:output_type -> broker.v1.LogsResponse
	14, // 20: broker.v1.BrokerService.CancelJob:output_type -> broker.v1.CancelJobResponse
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_broker_proto_init() }
func file_proto_broker_proto_init() {
	if File_proto_broker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_broker_proto_rawDesc), len(file_proto_broker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_broker_proto_goTypes,
		DependencyIndexes: file_proto_broker_proto_depIdxs,
		MessageInfos:      file_proto_broker_proto_msgTypes,
	}.Build()
	File_proto_broker_proto = out.File
	file_proto_broker_proto_goTypes = nil
	file_proto_broker_proto_depIdxs = nil
}
